### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by Jozer99** [Printrbot/printrboardmodernmarlin#11]
I am having a problem compiling and flashing the firmware per your directions in Windows.  I installed Marlin-conf using the executable on their Git site, and successfully import one of your configurations into Marlin-conf.  I set it to compile using the "at90USB1286-DFU" setting, then click compile.  

The first time I do this, the PlatformIO terminal pops up and shows it downloading a bunch of things (the last successful package being "LibraryManager: Installing c1921b4"), until it stops with the error:
`Error: Unknown board ID 'at90USB1286'`.  

Subsequent attempts to compile just give the error:

`Processing at90USB1286_DFU (platform: teensy; board: at90USB1286; framework: arduino)
Error: Unknown board ID 'at90USB1286'
Done.`

I've tried this with Marlin-conf versions 2.10.7 and 2.10.5, with the same result.  Any tips?

**Comment by drphil3d** [comment]
you have to select teensy20 from the menu, make sure you selected marlin 1.1.9 as far as I'm aware 2.0 wont compile

**Comment by Jozer99** [comment]
Changed to "teensy20", I get a very similar error:

`Processing teensy20 (platform: teensy; board: teensy20pp; framework: arduino)

Error: Unknown board ID 'teensy20pp'

Done.`

**Comment by kolakidd** [comment]
Solution to teensy20 issue is here: https://github.com/Printrbot/printrboardmodernmarlin/issues/8

**Comment by Jozer99** [comment]
I've also tried running Marlin-config in Ubuntu 18.04 (previously used Win10).  I get the same error.  Can you provide directions for working compilation?  If not, can I provide you with a Configuration.h file to compile?

**Comment by Jozer99** [comment]
@kolakidd That seems to have resolved the unknown board id error.  Now I get a bunch of warnings and eventually an error. I am attaching the log to this post.  I haven't changed anything but the bed size and enabled SD support.  
[errors.txt](https://github.com/Printrbot/printrboardmodernmarlin/files/2822872/errors.txt)

Edit: I can compile successfully if SD support is disabled.  The readme.md description states that SD support works, how do I enable it?

**Comment by wBrhy2** [comment]
> Solution to teensy20 issue is here: #8

why do we want teensy20 for the printrbot simple metal instead of at90USB1286_CDC ? when flashing with FLIP, I use at90USB1286

**Comment by drphil3d** [comment]
the options you choose in flip vs compiling using platform IO are different but same processor type
