### ISSUE TITLE
After flashing, cannot get into programming mode

### ISSUE THREAD

**Issue by Jozer99** [Printrbot/printrboardmodernmarlin#12]
After flashing the v0.6.5 .hex file on your site, I can no longer get into programming mode with my Rev F5 Printrboard.  Installing the jumper and resetting or power cycling does not result in the board being recognized as "programmable".  Programming by TINYusbISP also fails for the same reason; the board now refuses to go into programming mode.

**Comment by drphil3d** [comment]
If you flashed using an isp programmer you likely wiped out the bootloader

**Comment by drphil3d** [comment]
Did you download the repo as zip?
