### ISSUE TITLE
Offset XY location for the Simple Metal

### ISSUE THREAD

**Issue by evenlund** [Printrbot/printrboardmodernmarlin#14]
I have flashed "RevFv1.0_Printrbot_Simple_Metal_HB.hex" for my stock Simple Metal with printrboard F5. After that I ran all G-code found on the [referenced page in the instructions](https://docs.google.com/spreadsheets/d/1FntcZTm4M7FzUf9ej9DEmRYf1LaH76J8TU3VzK3Ox8g/pubhtml) for the Simple 1403. I have also added the startup gcode in some slicers.

Unfortunately the coordinates seems to be offset from what is correct resulting in prints close to the edge of the bed when the object is centered in the slicer.

Do I have to compile Marlin again with some special settings or can I use some g code (ie. M206) to fix this issue? Examples would be appreciated.

**Comment by drphil3d** [comment]
Looks like your lucky and I enabled SOFT_ENDSTOPS_MENU_ITEM which means you should be able to change the offsets using M206.
http://marlinfw.org/docs/gcode/M206.html

Just keep in mind a lot has changed with Marlin sense the last version that was on the Printrbot. 

I just noticed I put the wrong extruder steps per mm in firmware. its set to 94.5 and should be 96.00
I will fix that in the next release. for now just set it using
M92 E96.00
M500
