### ISSUE TITLE
M212 no longer works.... how do we calibrate now?

### ISSUE THREAD

**Issue by wBrhy2** [Printrbot/printrboardmodernmarlin#17]
I always used M212 to set the Z offset to adjust the printer, but M212 no longer works, and M206 doesn't seem to work the same way in that it in no way provides an offset that can go below the trigger point of the probe....

**Comment by kolakidd** [comment]
Have a look at the instructions on the wiki, there is a piece on setting the probe height.

https://github.com/Printrbot/printrboardmodernmarlin/wiki/Process-for-compiling-firmware

**Comment by wBrhy2** [comment]
Thanks! That 211 and 851 combination are the answer / new method.
