### ISSUE TITLE
Play Flashing, SD, and Bed Leveling

### ISSUE THREAD

**Issue by drewtm** [Printrbot/printrboardmodernmarlin#20]
I've had a few issues while putting this on my Printrbot Play. The one that seems most blocking is that flashing the firmware using the FLIP software requires me to leave the jumper on the board alone. If I try to follow the many instructions that I find online (install the boot jumper to start the machine in firmware flashing mode) it doesn't work. I did manage to get the firmware flashed and successfully run prints (with no jumpering), but it seems strange to me that the instructions that work for others would be irrelevant to my printer. Am I missing something important?

I haven't been able to compile the firmware myself, I'm just using one of the prebuilds for the Play that is available in the repository.

Also, the Play has an SD card slot (with no LCD or control panel of any kind) that seems to be unsupported in the Play build that I see in the repository. The only references to SD cards that I remember seeing documented around here are for SD cards on LCD control panels.

Lastly, although it is noted in the readme that three-point bed leveling works better for small beds (like the 100mm square standard build plate on the Play) there seems to be a 16-point grid enabled in the available Play build. Is that intentional?

I'd love to be able to connect to my printer, point it to a file on the SD card, and then disconnect to let it finish the print. I'd also like to have the 3-point leveling because I found it to make a better first layer, especially near the edges of the build plate. The compiling/flashing issue is less important in the end, other than as a way to work on my own problems.

Any thoughts on any of these points?

**Comment by drphil3d** [comment]
Yes these issues where addressed in recent releases. I believe I enabled SD card support, it's just that on the RevF board with limited space you have to decide what features are most important and SD card support takes something like 20% capacity.
