### ISSUE TITLE
Simple metal heated bed not reading out 

### ISSUE THREAD

**Issue by wBrhy2** [Printrbot/printrboardmodernmarlin#21]
Hello, I use octoprint and have been playing with different firmware configurations for the past few weeks. For some reason I can't get the heated bed temperature to be read (and as such no heating is possible). I have tried setting it myself and using the firmware v1.0 provided here.

I have tried measuring the thermistor, and it comes out at 100k ohm as it should.

Any ideas on how to troubleshoot this some more? Is there some way I can use the gcode terminal to probe stuff?

Thanks

Update : I've switch the hot-end and heated bed thermistors just to troubleshoot. The heated bed thermistor works just fine when plugged in the hot-end port. It seems the heated bed thermistor port just isn't picking up any reading. This was confirmed by putting the hot-end thermistor on it, still didn't get a reading.

**Comment by wBrhy2** [comment]
Sorry to bump my own message, but can anyone confirm a known firmware that works with the heated bed so I can test if it's my board?

**Comment by kolakidd** [comment]
I have a metal simple with a heated and extended bed, also running off Octoprint. The firmware and method I used is in the wiki, under compiling firmware.

It does sound like a firmware issue, but very stupid question: have you tried to read the temperatures by direct usb connection to pc with Octoprint?

**Comment by wBrhy2** [comment]
So you are using this firmware? RevFv1.0_Printrbot_Simple_Metal_HB.hex if so, That's what I'm using right now.


What do you cm by direct usb connecting? My printer is connected via USB to
a rpi running octopi.

**Comment by wBrhy2** [comment]
For the purpose of testing I connected via USB to my android device using gcodeprintr, it did not get any readings for the heated bed, but also returned a command not recognized error when I tried changing the temp... I guess I'll try reflashing again.

**Comment by wBrhy2** [comment]
Alright, I reflashed and it's fine..... I don't get it since I tried like 6 times, but after re-downloading it fresh then it worked. Thanks!

**Comment by drphil3d** [comment]
sorry I didn't see this issue until now for some reason didn't get a notification.
