### ISSUE TITLE
Simple Metal Post auto-leveling rapid move to X0, Y0, and Z up 10mm too rapid

### ISSUE THREAD

**Issue by unixunion** [Printrbot/printrboardmodernmarlin#24]
Hi, 

Can you possibly remove the POST auto-leveling rapid movement to 0,0,10 as its too fast for my machine, and its not nice having such a movement hard coded in post autoleveling. I cant seem to get the firmware compiled myself, as platformio is giving me hell to try and compile for at90USB1286_DFU. 

Thanks.

**Comment by drphil3d** [comment]
Sure, I can do that. You have to use Teensy20 to compile firmware. Personally I use Marlin-Config to compile mainly for the reason that all the dependencies for the development environment are already setup. https://github.com/akaJes/marlin-config/releases

Here is more information about compiling firmware
https://github.com/Printrbot/printrboardmodernmarlin/wiki

**Comment by drphil3d** [comment]
I removed the script from the latest version 2.01 available under releases.
If you want to compile it yourself the files are available along with the platformIO environment variables to make it compile. Choose option AT90usb1286_DFU
