### ISSUE TITLE
Cant change bed size with old commands on Printrbot Play fw1.1.9

### ISSUE THREAD

**Issue by gp1200ss** [Printrbot/printrboardmodernmarlin#25]
Hello,

I see this has been brought up before, but I am an extreme novice at this.  How can I get my settings of 203 x 203 x 130 mm back again?  I cant seem to use the old commands as stated in this forum.

What archive version can I use to setup the old way?

Thank you,
Johnny B

**Comment by kolakidd** [comment]
I set bed size in configuration.h see 5. here: https://github.com/Printrbot/printrboardmodernmarlin/wiki

If you're a novice, that wiki should get you through the process.

**Comment by gp1200ss** [comment]
Thank you! Will attempt asap....
________________________________

**Comment by drphil3d** [comment]
https://github.com/Printrbot/printrboardmodernmarlin/releases/tag/2.0.1
