### ISSUE TITLE
Z probe Logic reversed after firmware upgrade

### ISSUE THREAD

**Issue by Dragon2040** [Printrbot/printrboardmodernmarlin#27]
Upgraded the firmware on my Simple Metal RevD. Since doing so the logic on the probe is now reversed. 
M119 shows Triggered when no metal is detected, Open when metal is detected. This of course means when homing Z, it goes up then stops.
Rolled back to an earlier firmware, issue goes away and able to print normally.

Are you able to compile an updated file with the line change for the z probe?

Thanks.

**Comment by drphil3d** [comment]
I'll have to put that on my todo list

**Comment by drphil3d** [comment]
I compiled it for you, please test and let me know how it works
Marlin_2.0.1-Custom_Printrbot_Simple.Metal_RevD.Z-Probe.Inverted.Logic.hex
https://github.com/Printrbot/printrboardmodernmarlin/releases/tag/2.0.1

**Comment by GrumpyMetalGuy** [comment]
Hi, I just tried this firmware, and the Printrbot refused to connect to the Raspberry Pi running OctoPrint. Flashing back to the previous firmware works, but still have the inverted Z probe problem. Is it possible to try rebuilding the firmware?

Edit: Not sure if this is relevant, but in the 2.0.1 assets, the Play and Simple Metal inverted Z firmwares are the same size, although have some binary diffs in them. This is different to previous releases, where they were different sizes for the same builds. Not sure if this is relevant or not though!
