### ISSUE TITLE
Printrbot jr2 1402 firmware (?)

### ISSUE THREAD

**Issue by dealboy** [Printrbot/printrboardmodernmarlin#29]
Hi,

is any of these files compatible with a printrbot jr v2 (1402) ?
(mine has a RevD printrboard )
Or should I compile it?

thanks in advance
Yannis

**Comment by drphil3d** [comment]
just need machine dimensions

**Comment by drphil3d** [comment]
https://github.com/Printrbot/printrboardmodernmarlin/releases/tag/2.0.1
