### ISSUE TITLE
More complies for simple metal?

### ISSUE THREAD

**Issue by Jonny360** [Printrbot/printrboardmodernmarlin#30]
I have 8 simple metals  I need to update firmware on after a thermal runaway issue melted down one of my heatbeds. I have a mix of rev F and D boards. I also have a mix of heated and non heated beds, but all have e3d hot ends. Would it be possible to get more compiles than what is currently available for the simple metal? Rev D and Rev F with e3d hot end and one with and without HB?

**Comment by drphil3d** [comment]
https://github.com/Printrbot/printrboardmodernmarlin/releases/tag/2.0.1
