### ISSUE TITLE
LCD don't work with Marlin 2.0

### ISSUE THREAD

**Issue by jonathan-iap** [Printrbot/printrboardmodernmarlin#32]
Hi, 
I have a printrbot plus v2-1 (with wooden frame and LCD 20x4). 
So i want to change the nozzle and i need to set new parameters. 
But with Marlin 2.0 the LCD screen make whatever. 
It's display characters but all is mixing like an overflow and move all time.
Did you always try your firmware with this hardware ?
So  my motherboard is an printrboard revD .

**Comment by drphil3d** [comment]
It’s possible I may have not chosen the correct LCD. Are you using the genuine Printrbot LCD?

I set it up for the discount reprap lcd which is a very common lcd

**Comment by jonathan-iap** [comment]
So i think it's a problem with platformIO but i'm not totally sure. 
I say that because the LCD work when you compile with Arduino IDE. But the memory of the printrboard seem to small for marlin 2.0 when you active LCD and sd support. 
I have open an issue on [Marlin repo ](https://github.com/MarlinFirmware/Marlin/issues/16378)

**Comment by drphil3d** [comment]
Yeah there just isn’t enough memory on that processor. You can’t use more than 95% of the program memory if you want it to program successfully. The other 5% is being used by the boot loader.

**Comment by drphil3d** [comment]
This is what Brook says about the LCD
 “ The connections need to be checked and you absolutely have to run a ground wire between the screen pcb and the Printrboard. That usually takes care of it. But I have fixed that with a reflash too.

Bd”
