### ISSUE TITLE
2.0.1 Simple Metal Heated Bed

### ISSUE THREAD

**Issue by eehusky** [Printrbot/printrboardmodernmarlin#33]
https://github.com/Printrbot/printrboardmodernmarlin/releases/download/2.0.1/Marlin_2.0.1-Printrbot_Simple.Metal_HB_RevF.hex

This version does not seem to have the heated bed enabled.

Thanks for all the work keeping this updated.  I just dragged my printrbot out for the first time in a few years and the 1.0 version seems to be working great!

**Comment by drphil3d** [comment]
Oh ok, thanks for letting me know. I should figure out how to make a script to compile all the firmware for the different printers in a batch.

**Comment by Adams-Scott** [comment]
@eehusky, were you able to fix this or are you running the 1.0 version?
