### ISSUE TITLE
Printrbot Play HB w/ RepRapDiscount Smart Controller support

### ISSUE THREAD

**Issue by davidbrown-vsolvit** [Printrbot/printrboardmodernmarlin#39]
I'm trying to compile my own hex for a Printrbot Play with the heated bed upgrade and a RepRapDiscount Smart Controller using PlatformIO. I'm really getting nowhere. Could someone compile a hex for me and upload it to the repository? I'd greatly appreciate it.
Cheers!

**Comment by drphil3d** [comment]
The processor on the Printrboard only has 120k useable program memory, with all the features that give better print quality and ease of use you have to sacrifice some things. There isn't room for the display and SD card support.

**Comment by davidbrown-vsolvit** [comment]
Understood. Thank you Phillip.

--
David Brown
Software Engineer
VSolvit LLC
1305 Executive Blvd. Suite 150
Chesapeake, VA  23320
(757)998-8875 Ext. 286

**Comment by drphil3d** [comment]
What I recommend is using a raspberry pi with octoprint. The baby stepping feature is probably the most important of all.
