### ISSUE TITLE
README says "M815"?

### ISSUE THREAD

**Issue by aluhrs13** [Printrbot/printrboardmodernmarlin#4]
I just set this up on my Printrbot Simple Metal (and it appears to work perfectly!) but I think I found a slight issue in the readme. It says

```
 M815 Z-1.95 ;this is the default value
 M500 ;save
```

Should that be M851? - https://reprap.org/wiki/G-code#M851:_Set_Z-Probe_Offset

**Comment by drphil3d** [comment]
Yes it should! good catch! haha
