### ISSUE TITLE
G29 Z axis moves up on REVD versions of firmware

### ISSUE THREAD

**Issue by cpirnat** [Printrbot/printrboardmodernmarlin#40]
I have a Simple Metal with heated bed and a REVD board. I flashed the firmware and after a G28 then during a G29 the Z moves upwards away from the bed and never tries to probe downwards to detect the metal bed. Z stepper direction is normal otherwise.

**Comment by cpirnat** [comment]
Changed Z_MIN_PROBE_ENDSTOP_INVERTING setting it is functioning normally now.

**Comment by sirowain** [comment]
I have the same problem with the RevD firmware, can you share details on how to make it work?
