### ISSUE TITLE
How to set min/max position on Simple Metal Extended?

### ISSUE THREAD

**Issue by ColinTravis** [Printrbot/printrboardmodernmarlin#7]
Currently, my M211 reports my Min and Max at

echo: Min: X0.00 Y0.00 Z0.00

Max: X125.00 Y203.00 131.00

When the documentation states it should be at 
X152.40 Y152.40 Z152.40

The extended bed should bump it up to about X250, as well.

However, sending M211 just reports the value of the soft endstops, and doesn't allow me to set them.

What are my options?

**Comment by ColinTravis** [comment]
I'm just seeing the other issue reporting about software endstops. Closing this.

**Comment by drphil3d** [comment]
Unfortunately with marlin 1.1.9 I can't find a way to easily redefine the machine dimensions easily like you could in older versions of marlin. The smalls firmware will work the same on the simple metal

**Comment by ColinTravis** [comment]
Hmm, it looks to be a better option, but the dimensions are off for the simple metal extended. The extended bed changes the X to be 250. I tried compiling the firmware with an updated Configuration.h, but I keep getting an error thrown stating:

`Marlin/pins_PRINTRBOARD.h:65:4: error: #error "Oops! Make sure you have 'Teensy++ 2.0' or 'Printrboard' selected from the Tools -> Boards menu` 

I'm using the marlin-config gui to compile.

**Comment by Zakattacks** [comment]
According to https://github.com/Printrbot/printrboardmodernmarlin/issues/8 you have to manually change the teensy20 to teensy2. However, I have not had this issue.

**Comment by drphil3d** [comment]
https://github.com/Printrbot/printrboardmodernmarlin/releases/tag/2.0.1
